### ISSUE TITLE
Rename Users::AuthorizationFailedException

### ISSUE THREAD

**Issue by harigopal** [godreams/admin-server#1]
@ajaleelp The `AuthorizationFailedException` appears to be used when a _authorized_ user is not permitted to perform an action. The naming should be improved, since the used was logged in through `Users::AuthorizationService`.

**Comment by ajaleelp** [comment]
You mean an _authenticated_ user attempts an action he is not _authorized_ for ?

**Comment by harigopal** [comment]
You're right. Something's off about the naming scheme for related items though. 

`AuthorizationService` doesn't actually have anything to do with authorization. It's more like a `FindUserWithTokenService` or `AuthenticateTokenService`.

And I find `AuthorizationFailedException` confusing. That's more like a `NotPermittedException` to me.

**Comment by harigopal** [comment]
Also, the status code for the exception should probably be 403 (Forbidden) instead of 401 (Unauthorized). http://stackoverflow.com/a/6937030/1425158

**Comment by ajaleelp** [comment]
True that. A forbidden error makes much more sense. You want to tackle it right away or file a card?
