### ISSUE TITLE
All final receipts mailed to donors should be cc-ed to receipts@godreams.org

### ISSUE THREAD

**Issue by harigopal** [godreams/admin-server#36]
Receipts to be numbered in order of approval at NFH level.

**Comment by harigopal** [comment]
@adityasurneni The receipt number is currently the `id` number of the donation. This makes it trivial to map a receipt to a donation - is this acceptable, or should the receipt number generated anew for some reason?

**Comment by adityasurneni** [comment]
@harigopal This is from an accounting point of view. Not all transactions entered on the portal might be deposited and hence there might be few ids / receipt numbers missing in between which shouldn't be the case when  submitting the accounts to the IT dept.
